version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-backend-bot
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./database.db:/app/database.db
      - ./temp_audio:/app/temp_audio

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    restart: always
    ports:
      - "8080:80"